name: Hello world

on: 
  pull_request:
    branches:
      - main
      - features
      - realase

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Show a message
        run: echo "Hello world"
      - name: Multiple commands
        run: |
      