name: Containers

on: push
  

jobs:
  node-version:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27016"
    steps:
      - name: Post a user
        run: |
          curl -X POST http://localhost:3001/api/user \
          -H "Content-Type: application/json" \
          -d '{"address":"Cear√°", "username":"Lessa"}'
      - name: Get a user
        run: curl http://localhost:3001/api/users

        
      


      
      
      